base/api/urls.py
from django.urls import path
from . import views
from .views import UserRegistrationView,CreateRoomView

urlpatterns = [
    path('', views.getRoutes),
    path('rooms', views.getRooms),
    path('room/<str:pk>', views.getRoom),
    path('create-room', CreateRoomView.as_view()),
    path('deleteRoom/<str:id>', views.deleteRoom),
    path('userById/<str:id>',views.getUserById),
    path('search/<str:searchParam>', views.searchRooms),
    path('selectedUserFeed/<str:userId>',views.getSelectedUserFeed),
    path('topic/<str:topicName>', views.roomByTopic),
    path('topics', views.getTopics ),
    path('countTopics', views.getTopicsCount),
    path('topics/<str:topicName>', views.searchByTopic),
    path('register', UserRegistrationView.as_view()),
    path('login', views.login_user),
    path('update-profile', views.updateProfile),
    path('create-message', views.createMessage),
    path('activity/<str:searchWord>', views.getActivity),
    path('getCurrentUser', views.get_current_user),
    
    


]

base/urls.py
from django.urls import path
from base import views

urlpatterns = [
    
    path('login',views.loginPage, name='login'),
    path('registerPage',views.registerPage, name='registerPage'),
    path('logout',views.logOutUser, name='logout'),
    path('',views.home, name='home'),
    path('room/<str:pk>/',views.room, name='room'),
    path('profile/<str:pk>/',views.userProfile, name='profile'),
    path('create-room/',views.createRoom, name='create-room'),
    path('update-room/<str:pk>/',views.updateRoom, name='update-room'),
    path('update-user/',views.updateUser, name='update-user'),
    path('delete-room/<str:pk>/',views.deleteRoom, name='delete-room'),
    path('delete-message/<str:pk>/',views.deleteMessage, name='delete-message'),
    path('topics/', views.topicsPage, name="topics"),
    
]

firstDjangoProject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

    
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('api/', include('base.api.urls'))
]
 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser



class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email= models.EmailField(null=True, unique=True)
    bio = models.TextField(null=True)
    avatar = models.ImageField(null=True, default="spongebob.jpg")
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    # sabasaba Heroes173!
    pass
    
class Topic(models.Model):
    name = models.CharField(max_length=250)
    def __str__(self):
        return self.name
    
    
class Room(models.Model):
    host = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    topic = models.ForeignKey(Topic,on_delete=models.SET_NULL, null=True)
    name = models.CharField(max_length=120)
    description = models.TextField(null=True,blank=True)
    roomPhoto = models.ImageField(null=True, blank=True)
    participants = models.ManyToManyField(User,related_name='participants', blank=True)
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-update', 'created']
    
    def __str__(self):
        return self.name
    
class Message(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    room = models.ForeignKey(Room,on_delete=models.CASCADE)
    body = models.TextField()
    messagePhoto = models.ImageField(null=True)
    update = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.body[0:50]

base/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from .models import Room,User

    
class RoomForm(ModelForm):
    class Meta:
        model = Room
        fields = '__all__'
        exclude = ['host','participants']


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['avatar', 'name', 'username', 'email', 'bio']
        
        
class MyUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['name', 'username', 'email', 'password1', 'password2']

base/api/views.py
from rest_framework.decorators import api_view
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from .serializers import ActivitySerializer,RoomSerializer,TopicSerializer,TopicWithCountSerializer,UserSerializer,UserRegistrationSerializer,MessageSerializer
from base.models import Room,Topic,User,Message
from django.contrib.auth import authenticate
from django.http import JsonResponse
from rest_framework.authtoken.models import Token
from django.db.models import Q
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.decorators import api_view, authentication_classes, permission_classes
from rest_framework.authentication import TokenAuthentication
from rest_framework.permissions import IsAuthenticated


@api_view(['GET'])
def getRoutes(request):
    routes = [      
        'GET /api', 
        'GET /api/rooms',
        'GET /api/room/:id',
        'GET /api/user/:id',
        'GET /api/topics',
        'GET /api/topics/:topicName',
        'GET /api/countTopics/',
        'GET /api/user/',
        'POST /api/register',
    ]
    return Response(routes)

@api_view(['GET'])
def getUserById(request,id):
    user = User.objects.get(id=id)
    serializer = UserSerializer(user, many=False,context={'request': request})
    return Response(serializer.data)

@api_view(['GET'])
@authentication_classes([TokenAuthentication])
@permission_classes([IsAuthenticated])
def get_current_user(request):
    user = request.user
    user_data = UserSerializer(user, context={'request': request})
    return Response({'user':user_data.data})

@api_view(['GET'])
def getSelectedUserFeed(request,userId):
    user = User.objects.get(id=userId)
    rooms = Room.objects.filter(host=user)
    serializer = RoomSerializer(rooms, many=True,context={'request': request})
    return Response(serializer.data)

@api_view(['POST'])
def login_user(request):
    email = request.data.get('email') 
    password = request.data.get('password')
    user = authenticate(request, email=email, password=password)
    if user is not None:
        token, _ = Token.objects.get_or_create(user=user)
        user_data = UserSerializer(user,context={'request': request})
        return JsonResponse({'token': token.key, 'user':user_data.data})
    else:
        return JsonResponse({'error': 'Invalid credentials'}, status=400)

@api_view(['GET'])
def getRooms(request):
    rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True,context={'request': request})
    return Response(serializer.data)



@api_view(['POST'])
def createRoom(request):
    topic = request.data.get('topic')
    name = request.data.get('name')
    description = request.data.get('description')
    email = request.data.get("email")
    photo = request.data.get("roomPhoto")
    user = User.objects.get(email=email)
    topic, created = Topic.objects.get_or_create(name=topic)
    Room.objects.create(
            host=user,
            topic = topic,
            name = name,
            description = description,
            roomPhoto= photo
            
        )
    return JsonResponse({"message": "room created successfully"})
@api_view(['POST'])
def updateProfile(request):
    name = request.data.get('name')
    email = request.data.get('email')
    bio = request.data.get('bio')
    avatar = request.data.get('avatar')
    user = request.user
    if not user.is_authenticated:
        return Response({'error': 'User is not authenticated'}, status=status.HTTP_401_UNAUTHORIZED)

    try:
        # Update the User model fields
        if name:
            user.name = name  # Assuming 'name' maps to 'first_name' in User model
        if email:
            user.email = email
        if bio:
            user.bio = bio
        if avatar:
            user.avatar = avatar
        user.save()
        print(user.avatar)
        serializer = UserSerializer(user)
        return Response(serializer.data, status=status.HTTP_200_OK)
    except Exception as e:
        return Response({'error': str(e)}, status=status.HTTP_400_BAD_REQUEST)
@api_view(['DELETE'])
def deleteRoom(request,id):
    try:
        room = Room.objects.get(id=id)
        room.delete()
        return JsonResponse({'message': f'Room {id} was deleted successfully'}, status=200)
    except Room.DoesNotExist:
        return JsonResponse({'error': f'Room {id} does not exist'}, status=404)
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=500)

@api_view(['POST'])
def createMessage(request):
    message = request.data.get('message')
    roomId = int(request.data.get('roomId'))
    room = Room.objects.get(id=roomId) 
    email = request.data.get('email')
    user = User.objects.get(email=email)
    print(message,roomId,email)
    Message.objects.create(
            user=user,
            room=room,
            body=message,
        )
    return JsonResponse({"message": "message created successfully"})

@api_view(['GET'])
def get_user_details(request):
    user = request.user 
    serializer = UserSerializer(user)
    return Response(serializer.data)


@api_view(['GET'])
def getRoom(request,pk):
    room = Room.objects.get(id=pk)
    serializer = RoomSerializer(room, many=False,context={'request': request})
    return Response(serializer.data)
    
    
@api_view(['GET'])
def getTopics(request):
    topics = Topic.objects.all()
    serializer = TopicSerializer(topics,many=True)
    return Response(serializer.data)


@api_view(['GET'])
def searchByTopic(request,topicName):
    topics = Topic.objects.filter(name=topicName)
    serializer = TopicSerializer(topics,many=True)
    return Response(serializer.data)


@api_view(['GET'])
def roomByTopic(request,topicName):  
    if (topicName == 'All'):
      rooms = Room.objects.all()
    else:   
      topic = Topic.objects.get(name=topicName) 
      rooms = Room.objects.filter(topic=topic)  
    serializer = RoomSerializer(rooms, many=True,context={'request': request})
    return Response(serializer.data)

@api_view(['GET'])
def searchRooms(request, searchParam):
    if(searchParam):
        rooms= Room.objects.filter(Q(topic__name__icontains = searchParam) | Q(name__icontains=searchParam) | Q(description__icontains=searchParam))
    else:
        rooms = Room.objects.all()
    serializer = RoomSerializer(rooms, many=True,context={'request': request})
    return Response(serializer.data)
    
@api_view(['GET'])
def getTopicsCount(request):
    topicsObj = Topic.objects.all()
    topics = []
    for i in topicsObj:
        count = Room.objects.filter(topic=i).count()
        topic_data = TopicSerializer(i).data
        newEl = {'topic': topic_data, 'count': count}
        topics.append(newEl)
    print(topics)
    serializer = TopicWithCountSerializer(topics, many=True)
    return Response(serializer.data)


@api_view(['GET'])
def getActivity(request,searchWord):
    if(searchWord == 'All'):
        activity = Message.objects.all().order_by('-created')     
    else:
        activity = Message.objects.filter(Q(room__name__icontains=searchWord) | Q(room__description__icontains=searchWord) |Q(room__topic__name__contains=searchWord)).order_by('-created')
    serializer = ActivitySerializer(activity,many=True,context={'request': request})
    return Response(serializer.data)


class UserRegistrationView(APIView):
    def post(self, request): 
        serializer = UserRegistrationSerializer(data=request.data)
        if serializer.is_valid(): 
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class CreateRoomView(APIView):
    parser_classes = (MultiPartParser, FormParser)
    def post(self, request):
        topic = request.data.get('roomTopic')
        name = request.data.get('roomName')
        description = request.data.get('roomDescription')
        email = request.data.get('email')
        roomPhoto = request.FILES.get('roomPhoto')  # Get file

        user = User.objects.get(email=email)
        topic, created = Topic.objects.get_or_create(name=topic)
        room = Room.objects.create(
            host=user,
            topic=topic,
            name=name,
            description=description,
            roomPhoto=roomPhoto
        )
        return Response({"message": "Room created successfully"}, status=status.HTTP_201_CREATED)

base/templates/base/activity-component.html
<div class="activities">
  <div class="activities__header">
    <h2>Recent Activities</h2>
  </div>
  {% for activity in recentActivity %}
  <div class="activities__box">
    <div class="activities__boxHeader roomListRoom__header">
      <a href="{% url 'profile' activity.user.id %}" class="roomListRoom__author">
        <div class="avatar avatar--small">
          <img src="{{activity.user.avatar.url}}" />
        </div>
        <p>
          @{{activity.user.username}}
          <span>{{activity.created|timesince}} ago</span>
        </p>
      </a>
      {% if request.user.id == activity.user.id %}
      <div class="roomListRoom__actions">
        <a href="{% url "delete-message" activity.id %}">
          <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
            <title>delete</title>
            <path
              d="M30 4h-8v-3c0-0.553-0.447-1-1-1h-10c-0.553 0-1 0.447-1 1v3h-8v2h2v24c0 1.104 0.897 2 2 2h20c1.103 0 2-0.896 2-2v-24h2v-2h-0zM12 2h8v2h-8v-2zM26.002 30l-0.002 1v-1h-20v-24h20v24h0.002z">
            </path>
          </svg>
        </a>
      </div>
      {% endif %}
    </div>
    <div class="activities__boxContent">
      <p>replied to post “<a href="{% url "room" activity.room.id %}">{{activity.room}}</a>”</p>
      <div class="activities__boxRoomContent">
       {{activity.body}}
      </div>
    </div>
  </div>
  {% endfor %}

base/templates/base/delete.html
{% extends 'main.html' %}

{% block content %}
<main class="delete-item layout">
    <div class="container">
        <div class="layout__box">
            <div class="layout__boxHeader">
                <div class="layout__boxTitle">
                    <a href="{{request.META.HTTP_REFERER}}">
                        <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32"
                            viewBox="0 0 32 32">
                            <title>arrow-left</title>
                            <path
                                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
                            </path>
                        </svg>
                    </a>
                    <h3>Back</h3>
                </div>
            </div>
            <div class="layout__body">
                <form class="form" method="POST" action="">
                    {% csrf_token %}
                    <div class="form__group">
                        <p>Are you sure you want to delete "{{obj}}"?</p>
                    </div>

                    <div class="for__group">
                        <input class="btn btn--main" type="submit" value="Confirm" />
                    </div>

                </form>
            </div>
        </div>
    </div>
</main>
{% endblock content %}

base/templates/base/feed-component.html
{% for room in rooms %}
<div class="roomListRoom">
  <div class="roomListRoom__header">
    <a href="{% url "profile" room.host.id %}" class="roomListRoom__author">
      <div class="avatar avatar--small">
        <img src="{{room.host.avatar.url}}" />
      </div>
      <span>@{{room.host.username}}</span>
    </a>
    <div class="roomListRoom__actions">
      <span>{{room.created|timesince}} ago</span>
    </div>
  </div>
  <div class="roomListRoom__content">
    <a href="{% url "room" room.id %}">{{room.name}}</a>
    <p>
      {{room.body}}
    </p>
  </div>
  <div class="roomListRoom__meta">
    <a href="{% url "room" room.id %}" class="roomListRoom__joined">
      <svg
        version="1.1"
        xmlns="http://www.w3.org/2000/svg"
        width="32"
        height="32"
        viewBox="0 0 32 32"
      >
        <title>user-group</title>
        <path
          d="M30.539 20.766c-2.69-1.547-5.75-2.427-8.92-2.662 0.649 0.291 1.303 0.575 1.918 0.928 0.715 0.412 1.288 1.005 1.71 1.694 1.507 0.419 2.956 1.003 4.298 1.774 0.281 0.162 0.456 0.487 0.456 0.85v4.65h-4v2h5c0.553 0 1-0.447 1-1v-5.65c0-1.077-0.56-2.067-1.461-2.584z"
        ></path>
        <path
          d="M22.539 20.766c-6.295-3.619-14.783-3.619-21.078 0-0.901 0.519-1.461 1.508-1.461 2.584v5.65c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-5.651c0-1.075-0.56-2.064-1.461-2.583zM22 28h-20v-4.65c0-0.362 0.175-0.688 0.457-0.85 5.691-3.271 13.394-3.271 19.086 0 0.282 0.162 0.457 0.487 0.457 0.849v4.651z"
        ></path>
        <path
          d="M19.502 4.047c0.166-0.017 0.33-0.047 0.498-0.047 2.757 0 5 2.243 5 5s-2.243 5-5 5c-0.168 0-0.332-0.030-0.498-0.047-0.424 0.641-0.944 1.204-1.513 1.716 0.651 0.201 1.323 0.331 2.011 0.331 3.859 0 7-3.141 7-7s-3.141-7-7-7c-0.688 0-1.36 0.131-2.011 0.331 0.57 0.512 1.089 1.075 1.513 1.716z"
        ></path>
        <path
          d="M12 16c3.859 0 7-3.141 7-7s-3.141-7-7-7c-3.859 0-7 3.141-7 7s3.141 7 7 7zM12 4c2.757 0 5 2.243 5 5s-2.243 5-5 5-5-2.243-5-5c0-2.757 2.243-5 5-5z"
        ></path>
      </svg>
      {{room.participants.all.count}} Joined
    </a>
    <p class="roomListRoom__topic">{{room.topic}}</p>
  </div>
</div>
{% endfor %}
</div>

base/templates/base/home.html
{% extends "main.html" %} 
{% block content %}
<main class="layout layout--3">
  <div class="container">
    <!-- Topics Start -->
   {% include "base/topics-component.html" %}
    <!-- Topics End -->

    <!-- Room List Start -->
    <div class="roomList">
      <div class="mobile-menu">
        <form class="header__search">
          <label>
            <svg
              version="1.1"
              xmlns="http://www.w3.org/2000/svg"
              width="32"
              height="32"
              viewBox="0 0 32 32"
            >
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z"
              ></path>
            </svg>
            <input placeholder="Search for posts" />
          </label>
        </form>
        <div class="mobile-menuItems">
          <a class="btn btn--main btn--pill" href="#">Browse Topics</a>
          <a class="btn btn--main btn--pill" href="#">Recent Activities</a>
        </div>
      </div>
      <div class="roomList__header">
        <div>
          <h2>Study Room</h2>
          <p>{{count}} Rooms available</p>
        </div>
        <a class="btn btn--main" href="{% url 'create-room' %}">
          <svg
            version="1.1"
            xmlns="http://www.w3.org/2000/svg"
            width="32"
            height="32"
            viewBox="0 0 32 32"
          >
            <title>add</title>
            <path
              d="M16.943 0.943h-1.885v14.115h-14.115v1.885h14.115v14.115h1.885v-14.115h14.115v-1.885h-14.115v-14.115z"
            ></path>
          </svg>
          Create Room
        </a>
      </div>
      {% include "base/feed-component.html" %}
    <!-- Room List End -->

    <!-- Activities Start -->
    {% include "base/activity-component.html" %}
    <!-- Activities End -->
  </div>
</main>

{% endblock content %}

base/templates/base/login_registrate.html
{% extends 'main.html' %}

{% block content %}
<main class="auth layout">

  {% if page == 'login' %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Login</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %}
          <div class="form__group form__group">
            <label for="room_name">Email</label>
            <input id="username" name="email" type="email" placeholder="e.g. dennis_ivy@email.com" />
          </div>
          <div class=" form__group">
            <label for="password">Password</label>
            <input id="password" name="password" type="password"
              placeholder="&bull;&bull;&bull;&bull;&bull;&bull;&bull;&bull;" />
          </div>

          <button class="btn btn--main" type="submit">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
              </path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
              </path>
            </svg>

            Login
          </button>
        </form>

        <div class="auth__action">
          <p>Haven't signed up yet?</p>
          <a href="{% url 'registerPage' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
  {% else %}
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <h3>Register</h3>
        </div>
      </div>
      <div class="layout__body">
        <h2 class="auth__tagline">Find your study partner</h2>

        <form class="form" action="" method="POST">
          {% csrf_token %}

          {% for field in form %}
          <div class="form__group form__group">
            <label for="room_name">{{field.label}}</label>
            {{field}}
          </div>
          {% endfor %}


          <button class="btn btn--main" type="submit">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>lock</title>
              <path
                d="M27 12h-1v-2c0-5.514-4.486-10-10-10s-10 4.486-10 10v2h-1c-0.553 0-1 0.447-1 1v18c0 0.553 0.447 1 1 1h22c0.553 0 1-0.447 1-1v-18c0-0.553-0.447-1-1-1zM8 10c0-4.411 3.589-8 8-8s8 3.589 8 8v2h-16v-2zM26 30h-20v-16h20v16z">
              </path>
              <path
                d="M15 21.694v4.306h2v-4.306c0.587-0.348 1-0.961 1-1.694 0-1.105-0.895-2-2-2s-2 0.895-2 2c0 0.732 0.413 1.345 1 1.694z">
              </path>
            </svg>

            Register
          </button>
        </form>

        <div class="auth__action">
          <p>Already signed up yet?</p>
          <a href="{% url 'login' %}" class="btn btn--link">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
  {% endif %}
</main>
{% endblock content %}

base/templates/base/profile.html
{% extends "main.html" %}

{% block content %}
<main class="profile-page layout layout--3">
  <div class="container">
    <!-- Topics Start -->
    {% include "base/topics-component.html" %}
    <!-- Room List Start -->
    <div class="roomList">
      <div class="profile">
        <div class="profile__avatar">
          <div class="avatar avatar--large active">
            <img src="{{user.avatar.url}}" />
          </div>
        </div>
        {% if request.user.id == user.id %}
        <div class="profile__info">
          <h3>{{user.username}}</h3>
          <p>@{{user}}</p>
          <a href="{% url "update-user" %}" class="btn btn--main btn--pill">Edit Profile</a>
        </div>
        {% endif %}
        <div class="profile__about">
          <h3>About</h3>
          <p>
            {{user.bio}}
          </p>
        </div>
      </div>

      <div class="roomList__header">
        <div>
          <h2>Study Rooms Hosted by dennis_ivy</a>
          </h2>
        </div>
      </div>
      {% include "base/feed-component.html" %}
    <!-- Room List End -->

    <!-- Activities Start -->
    <div class="activities">
      <div class="activities__header">
        <h2>Recent Activities</h2>
      </div>
      {% for activity in recentActivity %}
      <div class="activities__box">
        <div class="activities__boxHeader roomListRoom__header">
          <a href="{% url 'profile' user.id %}" class="roomListRoom__author">
            <div class="avatar avatar--small">
              <img src="{{activity.user.avatar.url}}" />
            </div>
            <p>
              @{{user.username}}
              <span>{{activity.created|timesince}} ago</span>
            </p>
          </a>
          <div class="roomListRoom__actions">
            <a href="{% url "delete-message" activity.id %}">
              <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
                <title>delete</title>
                <path
                  d="M30 4h-8v-3c0-0.553-0.447-1-1-1h-10c-0.553 0-1 0.447-1 1v3h-8v2h2v24c0 1.104 0.897 2 2 2h20c1.103 0 2-0.896 2-2v-24h2v-2h-0zM12 2h8v2h-8v-2zM26.002 30l-0.002 1v-1h-20v-24h20v24h0.002z">
                </path>
              </svg>
            </a>
          </div>
        </div>
        <div class="activities__boxContent">
          <p>replied to post “<a href="{% url "room" activity.room.id %}">{{activity.room}}</a>”</p>
          <div class="activities__boxRoomContent">
           {{activity.body}}
          </div>
        </div>
      </div>
      {% endfor %}
    <!-- Activities End -->
  </div>
</main>





{% endblock content %}

{% comment %} <h1>User {{user.username}}</h1>

<div class='container'>
    <section>
        {% include "base/topics-component.html" %}
    </section>
    <section>
        {% include "base/feed-component.html" %}
    </section>
    <section>
        {% include "base/activity-component.html" %}
    </section>

</div> {% endcomment %}

base/templates/base/topics.html
{% extends 'main.html' %}

{% block content %}
<main class="create-room layout">
  <div class="container">
    <div class="layout__box">
      <div class="layout__boxHeader">
        <div class="layout__boxTitle">
          <a href="{% url 'home' %}">
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>arrow-left</title>
              <path
                d="M13.723 2.286l-13.723 13.714 13.719 13.714 1.616-1.611-10.96-10.96h27.625v-2.286h-27.625l10.965-10.965-1.616-1.607z">
              </path>
            </svg>
          </a>
          <h3>Browse Topics</h3>
        </div>
      </div>

      <div class="topics-page layout__body">
        <form action="" method="GET" class="header__search">
          <label>
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 32 32">
              <title>search</title>
              <path
                d="M32 30.586l-10.845-10.845c1.771-2.092 2.845-4.791 2.845-7.741 0-6.617-5.383-12-12-12s-12 5.383-12 12c0 6.617 5.383 12 12 12 2.949 0 5.649-1.074 7.741-2.845l10.845 10.845 1.414-1.414zM12 22c-5.514 0-10-4.486-10-10s4.486-10 10-10c5.514 0 10 4.486 10 10s-4.486 10-10 10z">
              </path>
            </svg>
            <input name="q" placeholder="Search for topics" />
          </label>
        </form>

        <ul class="topics__list">
          <li>
            <a href="{% url 'topics' %}" class="active">All <span>{{topics.count}}</span></a>
          </li>
          {% for topic in topics %}
          <li>
            <a href="{% url 'home' %}?q={{topic.name}}">{{ topic.name }} <span>{{topic.room_set.all.count}}</span></a>
          </li>
          {% endfor %}

        </ul>
      </div>
    </div>
  </div>
</main>

{% endblock content %}